@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package jooq.main.keys


import jooq.main.tables.FlywaySchemaHistory
import jooq.main.tables.KotlinVersion
import jooq.main.tables.Kotliner
import jooq.main.tables.Kug
import jooq.main.tables.records.FlywaySchemaHistoryRecord
import jooq.main.tables.records.KotlinVersionRecord
import jooq.main.tables.records.KotlinerRecord
import jooq.main.tables.records.KugRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val KOTLIN_VERSION_PKEY: UniqueKey<KotlinVersionRecord> = Internal.createUniqueKey(KotlinVersion.KOTLIN_VERSION, DSL.name("kotlin_version_pkey"), arrayOf(KotlinVersion.KOTLIN_VERSION.ID), true)
val KOTLINER_PKEY: UniqueKey<KotlinerRecord> = Internal.createUniqueKey(Kotliner.KOTLINER, DSL.name("kotliner_pkey"), arrayOf(Kotliner.KOTLINER.ID), true)
val UNIQUE_KOTLINER_EMAIL: UniqueKey<KotlinerRecord> = Internal.createUniqueKey(Kotliner.KOTLINER, DSL.name("unique_kotliner_email"), arrayOf(Kotliner.KOTLINER.NORMALIZED_EMAIL), true)
val UNIQUE_KOTLINER_NICKNAME: UniqueKey<KotlinerRecord> = Internal.createUniqueKey(Kotliner.KOTLINER, DSL.name("unique_kotliner_nickname"), arrayOf(Kotliner.KOTLINER.NICKNAME), true)
val KUG_PKEY: UniqueKey<KugRecord> = Internal.createUniqueKey(Kug.KUG, DSL.name("kug_pkey"), arrayOf(Kug.KUG.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val KUG__KUG_CREATED_BY_FKEY: ForeignKey<KugRecord, KotlinerRecord> = Internal.createForeignKey(Kug.KUG, DSL.name("kug_created_by_fkey"), arrayOf(Kug.KUG.CREATED_BY), jooq.main.keys.KOTLINER_PKEY, arrayOf(Kotliner.KOTLINER.ID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
val KUG__KUG_UPDATED_BY_FKEY: ForeignKey<KugRecord, KotlinerRecord> = Internal.createForeignKey(Kug.KUG, DSL.name("kug_updated_by_fkey"), arrayOf(Kug.KUG.UPDATED_BY), jooq.main.keys.KOTLINER_PKEY, arrayOf(Kotliner.KOTLINER.ID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
