/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables


import jooq.main.Public
import jooq.main.keys.ARTICLE_AUTHOR_PKEY
import jooq.main.keys.ARTICLE_AUTHOR__ARTICLE_AUTHOR_ARTICLE_ID_FKEY
import jooq.main.keys.ARTICLE_AUTHOR__ARTICLE_AUTHOR_KOTLINER_ID_FKEY
import jooq.main.tables.Article.ArticlePath
import jooq.main.tables.Kotliner.KotlinerPath
import jooq.main.tables.records.ArticleAuthorRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ArticleAuthor(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ArticleAuthorRecord>?,
    parentPath: InverseForeignKey<out Record, ArticleAuthorRecord>?,
    aliased: Table<ArticleAuthorRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ArticleAuthorRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.article_author</code>
         */
        val ARTICLE_AUTHOR: ArticleAuthor = ArticleAuthor()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ArticleAuthorRecord> = ArticleAuthorRecord::class.java

    /**
     * The column <code>public.article_author.article_id</code>.
     */
    val ARTICLE_ID: TableField<ArticleAuthorRecord, Long?> = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.article_author.kotliner_id</code>.
     */
    val KOTLINER_ID: TableField<ArticleAuthorRecord, Long?> = createField(DSL.name("kotliner_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ArticleAuthorRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ArticleAuthorRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ArticleAuthorRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.article_author</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.article_author</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.article_author</code> table reference
     */
    constructor(): this(DSL.name("article_author"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ArticleAuthorRecord>?, parentPath: InverseForeignKey<out Record, ArticleAuthorRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ARTICLE_AUTHOR, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ArticleAuthorPath : ArticleAuthor, Path<ArticleAuthorRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ArticleAuthorRecord>?, parentPath: InverseForeignKey<out Record, ArticleAuthorRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ArticleAuthorRecord>): super(alias, aliased)
        override fun `as`(alias: String): ArticleAuthorPath = ArticleAuthorPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ArticleAuthorPath = ArticleAuthorPath(alias, this)
        override fun `as`(alias: Table<*>): ArticleAuthorPath = ArticleAuthorPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ArticleAuthorRecord> = ARTICLE_AUTHOR_PKEY
    override fun getReferences(): List<ForeignKey<ArticleAuthorRecord, *>> = listOf(ARTICLE_AUTHOR__ARTICLE_AUTHOR_ARTICLE_ID_FKEY, ARTICLE_AUTHOR__ARTICLE_AUTHOR_KOTLINER_ID_FKEY)

    private lateinit var _article: ArticlePath

    /**
     * Get the implicit join path to the <code>public.article</code> table.
     */
    fun article(): ArticlePath {
        if (!this::_article.isInitialized)
            _article = ArticlePath(this, ARTICLE_AUTHOR__ARTICLE_AUTHOR_ARTICLE_ID_FKEY, null)

        return _article;
    }

    val article: ArticlePath
        get(): ArticlePath = article()

    private lateinit var _kotliner: KotlinerPath

    /**
     * Get the implicit join path to the <code>public.kotliner</code> table.
     */
    fun kotliner(): KotlinerPath {
        if (!this::_kotliner.isInitialized)
            _kotliner = KotlinerPath(this, ARTICLE_AUTHOR__ARTICLE_AUTHOR_KOTLINER_ID_FKEY, null)

        return _kotliner;
    }

    val kotliner: KotlinerPath
        get(): KotlinerPath = kotliner()
    override fun `as`(alias: String): ArticleAuthor = ArticleAuthor(DSL.name(alias), this)
    override fun `as`(alias: Name): ArticleAuthor = ArticleAuthor(alias, this)
    override fun `as`(alias: Table<*>): ArticleAuthor = ArticleAuthor(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ArticleAuthor = ArticleAuthor(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ArticleAuthor = ArticleAuthor(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ArticleAuthor = ArticleAuthor(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ArticleAuthor = ArticleAuthor(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ArticleAuthor = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ArticleAuthor = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ArticleAuthor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ArticleAuthor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ArticleAuthor = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ArticleAuthor = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ArticleAuthor = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ArticleAuthor = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ArticleAuthor = where(DSL.notExists(select))
}
