/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables


import jooq.main.Public
import jooq.main.keys.BOOK_LIBRARY_PKEY
import jooq.main.keys.BOOK_LIBRARY__BOOK_LIBRARY_BOOK_ID_FKEY
import jooq.main.keys.BOOK_LIBRARY__BOOK_LIBRARY_LIBRARY_ID_FKEY
import jooq.main.tables.Book.BookPath
import jooq.main.tables.Library.LibraryPath
import jooq.main.tables.records.BookLibraryRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookLibrary(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BookLibraryRecord>?,
    parentPath: InverseForeignKey<out Record, BookLibraryRecord>?,
    aliased: Table<BookLibraryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BookLibraryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.book_library</code>
         */
        val BOOK_LIBRARY: BookLibrary = BookLibrary()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BookLibraryRecord> = BookLibraryRecord::class.java

    /**
     * The column <code>public.book_library.book_id</code>.
     */
    val BOOK_ID: TableField<BookLibraryRecord, Long?> = createField(DSL.name("book_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.book_library.library_id</code>.
     */
    val LIBRARY_ID: TableField<BookLibraryRecord, Long?> = createField(DSL.name("library_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BookLibraryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BookLibraryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BookLibraryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.book_library</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.book_library</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.book_library</code> table reference
     */
    constructor(): this(DSL.name("book_library"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookLibraryRecord>?, parentPath: InverseForeignKey<out Record, BookLibraryRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BOOK_LIBRARY, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BookLibraryPath : BookLibrary, Path<BookLibraryRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BookLibraryRecord>?, parentPath: InverseForeignKey<out Record, BookLibraryRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BookLibraryRecord>): super(alias, aliased)
        override fun `as`(alias: String): BookLibraryPath = BookLibraryPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BookLibraryPath = BookLibraryPath(alias, this)
        override fun `as`(alias: Table<*>): BookLibraryPath = BookLibraryPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<BookLibraryRecord> = BOOK_LIBRARY_PKEY
    override fun getReferences(): List<ForeignKey<BookLibraryRecord, *>> = listOf(BOOK_LIBRARY__BOOK_LIBRARY_BOOK_ID_FKEY, BOOK_LIBRARY__BOOK_LIBRARY_LIBRARY_ID_FKEY)

    private lateinit var _book: BookPath

    /**
     * Get the implicit join path to the <code>public.book</code> table.
     */
    fun book(): BookPath {
        if (!this::_book.isInitialized)
            _book = BookPath(this, BOOK_LIBRARY__BOOK_LIBRARY_BOOK_ID_FKEY, null)

        return _book;
    }

    val book: BookPath
        get(): BookPath = book()

    private lateinit var _library: LibraryPath

    /**
     * Get the implicit join path to the <code>public.library</code> table.
     */
    fun library(): LibraryPath {
        if (!this::_library.isInitialized)
            _library = LibraryPath(this, BOOK_LIBRARY__BOOK_LIBRARY_LIBRARY_ID_FKEY, null)

        return _library;
    }

    val library: LibraryPath
        get(): LibraryPath = library()
    override fun `as`(alias: String): BookLibrary = BookLibrary(DSL.name(alias), this)
    override fun `as`(alias: Name): BookLibrary = BookLibrary(alias, this)
    override fun `as`(alias: Table<*>): BookLibrary = BookLibrary(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BookLibrary = BookLibrary(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BookLibrary = BookLibrary(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BookLibrary = BookLibrary(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BookLibrary = BookLibrary(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BookLibrary = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BookLibrary = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BookLibrary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BookLibrary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BookLibrary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BookLibrary = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BookLibrary = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BookLibrary = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BookLibrary = where(DSL.notExists(select))
}
