/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables


import java.time.OffsetDateTime

import jooq.main.Public
import jooq.main.keys.DM_LIKES_PKEY
import jooq.main.tables.records.DmLikesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DmLikes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DmLikesRecord>?,
    parentPath: InverseForeignKey<out Record, DmLikesRecord>?,
    aliased: Table<DmLikesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DmLikesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.dm_likes</code>
         */
        val DM_LIKES: DmLikes = DmLikes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DmLikesRecord> = DmLikesRecord::class.java

    /**
     * The column <code>public.dm_likes.entity_id</code>.
     */
    val ENTITY_ID: TableField<DmLikesRecord, Long?> = createField(DSL.name("entity_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.dm_likes.likes</code>.
     */
    val LIKES: TableField<DmLikesRecord, Int?> = createField(DSL.name("likes"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.dm_likes.dislikes</code>.
     */
    val DISLIKES: TableField<DmLikesRecord, Int?> = createField(DSL.name("dislikes"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.dm_likes.updated</code>.
     */
    val UPDATED: TableField<DmLikesRecord, OffsetDateTime?> = createField(DSL.name("updated"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<DmLikesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DmLikesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DmLikesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.dm_likes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.dm_likes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.dm_likes</code> table reference
     */
    constructor(): this(DSL.name("dm_likes"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<DmLikesRecord> = DM_LIKES_PKEY
    override fun `as`(alias: String): DmLikes = DmLikes(DSL.name(alias), this)
    override fun `as`(alias: Name): DmLikes = DmLikes(alias, this)
    override fun `as`(alias: Table<*>): DmLikes = DmLikes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): DmLikes = DmLikes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): DmLikes = DmLikes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): DmLikes = DmLikes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): DmLikes = DmLikes(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): DmLikes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): DmLikes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): DmLikes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): DmLikes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): DmLikes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DmLikes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DmLikes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): DmLikes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): DmLikes = where(DSL.notExists(select))
}
