/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables


import java.time.OffsetDateTime

import jooq.main.Public
import jooq.main.keys.ARTICLE_KOTLIN_VERSION__ARTICLE_KOTLIN_VERSION_KOTLIN_VERSION_ID_FKEY
import jooq.main.keys.KOTLIN_VERSION_PKEY
import jooq.main.tables.Article.ArticlePath
import jooq.main.tables.ArticleKotlinVersion.ArticleKotlinVersionPath
import jooq.main.tables.records.KotlinVersionRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class KotlinVersion(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, KotlinVersionRecord>?,
    parentPath: InverseForeignKey<out Record, KotlinVersionRecord>?,
    aliased: Table<KotlinVersionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<KotlinVersionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.kotlin_version</code>
         */
        val KOTLIN_VERSION: KotlinVersion = KotlinVersion()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<KotlinVersionRecord> = KotlinVersionRecord::class.java

    /**
     * The column <code>public.kotlin_version.id</code>.
     */
    val ID: TableField<KotlinVersionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.kotlin_version.title</code>.
     */
    val TITLE: TableField<KotlinVersionRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column <code>public.kotlin_version.created</code>.
     */
    val CREATED: TableField<KotlinVersionRecord, OffsetDateTime?> = createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<KotlinVersionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<KotlinVersionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<KotlinVersionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.kotlin_version</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.kotlin_version</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.kotlin_version</code> table reference
     */
    constructor(): this(DSL.name("kotlin_version"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KotlinVersionRecord>?, parentPath: InverseForeignKey<out Record, KotlinVersionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, KOTLIN_VERSION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class KotlinVersionPath : KotlinVersion, Path<KotlinVersionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, KotlinVersionRecord>?, parentPath: InverseForeignKey<out Record, KotlinVersionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<KotlinVersionRecord>): super(alias, aliased)
        override fun `as`(alias: String): KotlinVersionPath = KotlinVersionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): KotlinVersionPath = KotlinVersionPath(alias, this)
        override fun `as`(alias: Table<*>): KotlinVersionPath = KotlinVersionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<KotlinVersionRecord, Long?> = super.getIdentity() as Identity<KotlinVersionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<KotlinVersionRecord> = KOTLIN_VERSION_PKEY

    private lateinit var _articleKotlinVersion: ArticleKotlinVersionPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.article_kotlin_version</code> table
     */
    fun articleKotlinVersion(): ArticleKotlinVersionPath {
        if (!this::_articleKotlinVersion.isInitialized)
            _articleKotlinVersion = ArticleKotlinVersionPath(this, null, ARTICLE_KOTLIN_VERSION__ARTICLE_KOTLIN_VERSION_KOTLIN_VERSION_ID_FKEY.inverseKey)

        return _articleKotlinVersion;
    }

    val articleKotlinVersion: ArticleKotlinVersionPath
        get(): ArticleKotlinVersionPath = articleKotlinVersion()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.article</code> table
     */
    val article: ArticlePath
        get(): ArticlePath = articleKotlinVersion().article()
    override fun `as`(alias: String): KotlinVersion = KotlinVersion(DSL.name(alias), this)
    override fun `as`(alias: Name): KotlinVersion = KotlinVersion(alias, this)
    override fun `as`(alias: Table<*>): KotlinVersion = KotlinVersion(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): KotlinVersion = KotlinVersion(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): KotlinVersion = KotlinVersion(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): KotlinVersion = KotlinVersion(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): KotlinVersion = KotlinVersion(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): KotlinVersion = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): KotlinVersion = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): KotlinVersion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): KotlinVersion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): KotlinVersion = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): KotlinVersion = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): KotlinVersion = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): KotlinVersion = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): KotlinVersion = where(DSL.notExists(select))
}
