/*
 * This file is generated by jOOQ.
 */
package jooq.main.enums


import jooq.main.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class KugStatusEnum(@get:JvmName("literal") public val literal: String) : EnumType {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE"),
    HIDDEN("HIDDEN"),
    DELETED("DELETED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "kug_status_enum"
    override fun getLiteral(): String = literal
}
