= Contribution Guidelines


== Adding to this list


This awesome list contains two views: standard github page view, and nice website with search.
You can contribute in this list in few ways:

1. Create issue with you link. - easiest way, if you doesn't have a lot time or you can't install node.js for some reason.
2. Edit ./app/Kotlin.js directly, and then run `npm run readme`. - For regular users of node.js.

I really appreciate any of this ways, so please feel free to create issues,
instead of spending time figuring out of how to install node.js for example.

Any links will be check for their value for Kotlin.

*Happy contributing!*

== How to update webpage?

Create file `settings.js` in root folder (same folder where this file placed) with following content:
----
// settings.js
exports.default = {
    user: 'YourGithubUsername',
    pass: 'Token, which you can generate here: https://github.com/settings/tokens'
};
----

. Now you can run `npm run build`, this command will generate json for website, website and readme
. Then commit and push `Kotlin.js` and `README.adoc`, and create pull request.
. Now switch branch to `gh-pages`, copy `bundle.js` from `dist` folder to root folder.
. Commit, push, create pull request.
