CREATE TABLE KOTLINER
(
    ID               BIGSERIAL    NOT NULL,
    AVATAR           VARCHAR(500) NULL,
    DESCRIPTION      TEXT         NOT NULL,
    NORMALIZED_EMAIL VARCHAR(500) NOT NULL,
    ORIGINAL_EMAIL   VARCHAR(500) NOT NULL,
    FIRST_NAME       VARCHAR(100) NULL,
    LAST_NAME        VARCHAR(100) NULL,
    NICKNAME         VARCHAR(100) NOT NULL,
    PASSWORD         VARCHAR(500) NOT NULL,
    TOTP             VARCHAR(500) NULL,
    PRIMARY KEY (ID),
    CONSTRAINT unique_kotliner_email UNIQUE (NORMALIZED_EMAIL),
    CONSTRAINT unique_kotliner_nickname UNIQUE (NICKNAME)
);

CREATE TABLE KOTLINER_META
(
    KOTLINER_ID BIGINT       NOT NULL,
    ID          BIGSERIAL    NOT NULL,
    META_KEY    VARCHAR(500) NOT NULL,
    META_VALUE  TEXT         NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT unique_kotliner_meta UNIQUE (META_KEY, KOTLINER_ID)
);

ALTER TABLE KOTLINER_META
    ADD FOREIGN KEY (KOTLINER_ID) REFERENCES KOTLINER (ID);

