CREATE TABLE KUG
(
    ID        BIGSERIAL    NOT NULL,
    CONTINENT VARCHAR(500) NOT NULL,
    NAME      VARCHAR(500) NOT NULL,
    COUNTRY   VARCHAR(500) NOT NULL,
    URL       VARCHAR(500) NOT NULL,
    LATITUDE  DOUBLE PRECISION NULL,
    LONGITUDE DOUBLE PRECISION NULL,
    CREATED   DATE         NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE KOTLINER_KUG
(
    KOTLINER_ID BIGINT NOT NULL,
    KUG_ID      BIGINT NOT NULL,
    JOIN_DATE   DATE   NOT NULL,
    CONSTRAINT unique_kotliner_kug UNIQUE (KOTLINER_ID)
);

ALTER TABLE KOTLINER_KUG
    ADD FOREIGN KEY (KOTLINER_ID) REFERENCES KOTLINER (ID);

ALTER TABLE KOTLINER_KUG
    ADD FOREIGN KEY (KUG_ID) REFERENCES KUG (ID);

