/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.records


import java.time.OffsetDateTime

import jooq.main.tables.Bookmark

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookmarkRecord() : UpdatableRecordImpl<BookmarkRecord>(Bookmark.BOOKMARK) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var language: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var url: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var thumbnail: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var created: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updated: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised BookmarkRecord
     */
    constructor(id: Long? = null, title: String? = null, description: String? = null, language: String? = null, url: String? = null, thumbnail: String? = null, created: OffsetDateTime? = null, updated: OffsetDateTime? = null): this() {
        this.id = id
        this.title = title
        this.description = description
        this.language = language
        this.url = url
        this.thumbnail = thumbnail
        this.created = created
        this.updated = updated
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookmarkRecord
     */
    constructor(value: jooq.main.tables.pojos.Bookmark?): this() {
        if (value != null) {
            this.id = value.id
            this.title = value.title
            this.description = value.description
            this.language = value.language
            this.url = value.url
            this.thumbnail = value.thumbnail
            this.created = value.created
            this.updated = value.updated
            resetChangedOnNotNull()
        }
    }
}
