/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.records


import jooq.main.tables.BookLibrary

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookLibraryRecord() : UpdatableRecordImpl<BookLibraryRecord>(BookLibrary.BOOK_LIBRARY) {

    open var bookId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var libraryId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised BookLibraryRecord
     */
    constructor(bookId: Long? = null, libraryId: Long? = null): this() {
        this.bookId = bookId
        this.libraryId = libraryId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookLibraryRecord
     */
    constructor(value: jooq.main.tables.pojos.BookLibrary?): this() {
        if (value != null) {
            this.bookId = value.bookId
            this.libraryId = value.libraryId
            resetChangedOnNotNull()
        }
    }
}
