/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.records


import java.time.OffsetDateTime

import jooq.main.tables.KotlinVersion

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class KotlinVersionRecord() : UpdatableRecordImpl<KotlinVersionRecord>(KotlinVersion.KOTLIN_VERSION) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var created: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised KotlinVersionRecord
     */
    constructor(id: Long? = null, title: String? = null, created: OffsetDateTime? = null): this() {
        this.id = id
        this.title = title
        this.created = created
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised KotlinVersionRecord
     */
    constructor(value: jooq.main.tables.pojos.KotlinVersion?): this() {
        if (value != null) {
            this.id = value.id
            this.title = value.title
            this.created = value.created
            resetChangedOnNotNull()
        }
    }
}
