/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.records


import jooq.main.tables.VideoSpeaker

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideoSpeakerRecord() : UpdatableRecordImpl<VideoSpeakerRecord>(VideoSpeaker.VIDEO_SPEAKER) {

    open var videoId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var kotlinerId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised VideoSpeakerRecord
     */
    constructor(videoId: Long? = null, kotlinerId: Long? = null): this() {
        this.videoId = videoId
        this.kotlinerId = kotlinerId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised VideoSpeakerRecord
     */
    constructor(value: jooq.main.tables.pojos.VideoSpeaker?): this() {
        if (value != null) {
            this.videoId = value.videoId
            this.kotlinerId = value.kotlinerId
            resetChangedOnNotNull()
        }
    }
}
