/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.records


import jooq.main.tables.VideoLibrary

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideoLibraryRecord() : UpdatableRecordImpl<VideoLibraryRecord>(VideoLibrary.VIDEO_LIBRARY) {

    open var videoId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var libraryId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised VideoLibraryRecord
     */
    constructor(videoId: Long? = null, libraryId: Long? = null): this() {
        this.videoId = videoId
        this.libraryId = libraryId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised VideoLibraryRecord
     */
    constructor(value: jooq.main.tables.pojos.VideoLibrary?): this() {
        if (value != null) {
            this.videoId = value.videoId
            this.libraryId = value.libraryId
            resetChangedOnNotNull()
        }
    }
}
