CREATE TABLE KOTLIN_VERSION
(
    ID      BIGINT PRIMARY KEY                DEFAULT nextval('ENTITY_ID_SEQ'),
    VALUE   VARCHAR(500)             NOT NULL,
    CREATED TIMESTAMP WITH TIME ZONE NOT NULL,
    DISPLAY BOOLEAN                  NOT NULL DEFAULT FALSE
);
