CREATE TYPE KUG_STATUS_ENUM AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'HIDDEN',
    'DELETED'
    );

CREATE TABLE KUG
(
    ID         BIGINT PRIMARY KEY                DEFAULT nextval('ENTITY_ID_SEQ'),
    CREATED    TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED    TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY BIGINT                   NULL REFERENCES KOTLINER (ID),
    UPDATED_BY BIGINT                   NOT NULL REFERENCES KOTLINER (ID),
    STATUS     KUG_STATUS_ENUM          NOT NULL,
    CONTINENT  VARCHAR(500)             NOT NULL,
    NAME       VARCHAR(500)             NOT NULL,
    COUNTRY    VARCHAR(500)             NOT NULL,
    URL        VARCHAR(500)             NOT NULL,
    SLUG       VARCHAR(500)             NOT NULL,
    LATITUDE   DOUBLE PRECISION         NULL,
    LONGITUDE  DOUBLE PRECISION         NULL,
    VERSION    BIGINT                   NOT NULL DEFAULT 0
);
