/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.daos


import java.time.OffsetDateTime

import jooq.main.tables.Video
import jooq.main.tables.records.VideoRecord

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VideoDao(configuration: Configuration?) : DAOImpl<VideoRecord, jooq.main.tables.pojos.Video, Long>(Video.VIDEO, jooq.main.tables.pojos.Video::class.java, configuration) {

    /**
     * Create a new VideoDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: jooq.main.tables.pojos.Video): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): jooq.main.tables.pojos.Video? = fetchOne(Video.VIDEO.ID, value)

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTitle(lowerInclusive: String?, upperInclusive: String?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.TITLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    fun fetchByTitle(vararg values: String): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.TITLE, *values)

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfDescription(lowerInclusive: String?, upperInclusive: String?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.DESCRIPTION, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    fun fetchByDescription(vararg values: String): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.DESCRIPTION, *values)

    /**
     * Fetch records that have <code>language BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLanguage(lowerInclusive: String?, upperInclusive: String?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.LANGUAGE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>language IN (values)</code>
     */
    fun fetchByLanguage(vararg values: String): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.LANGUAGE, *values)

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUrl(lowerInclusive: String?, upperInclusive: String?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.URL, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    fun fetchByUrl(vararg values: String): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.URL, *values)

    /**
     * Fetch records that have <code>duration BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfDuration(lowerInclusive: Int?, upperInclusive: Int?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.DURATION, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    fun fetchByDuration(vararg values: Int): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.DURATION, *values.toTypedArray())

    /**
     * Fetch records that have <code>thumbnail BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfThumbnail(lowerInclusive: String?, upperInclusive: String?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.THUMBNAIL, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>thumbnail IN (values)</code>
     */
    fun fetchByThumbnail(vararg values: String): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.THUMBNAIL, *values)

    /**
     * Fetch records that have <code>published BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfPublished(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.PUBLISHED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>published IN (values)</code>
     */
    fun fetchByPublished(vararg values: OffsetDateTime): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.PUBLISHED, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: OffsetDateTime): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.CREATED, *values)

    /**
     * Fetch records that have <code>updated BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUpdated(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<jooq.main.tables.pojos.Video> = fetchRange(Video.VIDEO.UPDATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>updated IN (values)</code>
     */
    fun fetchByUpdated(vararg values: OffsetDateTime): List<jooq.main.tables.pojos.Video> = fetch(Video.VIDEO.UPDATED, *values)
}
