/*
 * This file is generated by jOOQ.
 */
package link.kotlin.server.jooq.main.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class FlywaySchemaHistory(
    var installedRank: Int? = null,
    var version: String? = null,
    var description: String? = null,
    var type: String? = null,
    var script: String? = null,
    var checksum: Int? = null,
    var installedBy: String? = null,
    var installedOn: LocalDateTime? = null,
    var executionTime: Int? = null,
    var success: Boolean? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("FlywaySchemaHistory (")

        sb.append(installedRank)
        sb.append(", ").append(version)
        sb.append(", ").append(description)
        sb.append(", ").append(type)
        sb.append(", ").append(script)
        sb.append(", ").append(checksum)
        sb.append(", ").append(installedBy)
        sb.append(", ").append(installedOn)
        sb.append(", ").append(executionTime)
        sb.append(", ").append(success)

        sb.append(")")
        return sb.toString()
    }
}
