/*
 * This file is generated by jOOQ.
 */
package link.kotlin.server.jooq.main.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Kotliner(
    var id: Long? = null,
    var avatar: String? = null,
    var description: String? = null,
    var normalizedEmail: String? = null,
    var originalEmail: String? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var nickname: String? = null,
    var password: String? = null,
    var totp: String? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("Kotliner (")

        sb.append(id)
        sb.append(", ").append(avatar)
        sb.append(", ").append(description)
        sb.append(", ").append(normalizedEmail)
        sb.append(", ").append(originalEmail)
        sb.append(", ").append(firstName)
        sb.append(", ").append(lastName)
        sb.append(", ").append(nickname)
        sb.append(", ").append(password)
        sb.append(", ").append(totp)

        sb.append(")")
        return sb.toString()
    }
}
