/*
 * This file is generated by jOOQ.
 */
package link.kotlin.server.jooq.main.tables.references


import link.kotlin.server.jooq.main.tables.FlywaySchemaHistory
import link.kotlin.server.jooq.main.tables.Kotliner
import link.kotlin.server.jooq.main.tables.KotlinerKug
import link.kotlin.server.jooq.main.tables.KotlinerMeta
import link.kotlin.server.jooq.main.tables.Kug



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.kotliner</code>.
 */
val KOTLINER: Kotliner = Kotliner.KOTLINER

/**
 * The table <code>public.kotliner_kug</code>.
 */
val KOTLINER_KUG: KotlinerKug = KotlinerKug.KOTLINER_KUG

/**
 * The table <code>public.kotliner_meta</code>.
 */
val KOTLINER_META: KotlinerMeta = KotlinerMeta.KOTLINER_META

/**
 * The table <code>public.kug</code>.
 */
val KUG: Kug = Kug.KUG
