###
POST {{host}}/register
Content-Type: application/json

{
    "nickname": "IRus",
    "email": "ruslan@heapy.io",
    "password": [
        "w",
        "o",
        "r",
        "l",
        "d"
    ]
}

###
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "ruslan@heapy.io",
    "password": [
        "w",
        "o",
        "r",
        "l",
        "d"
    ]
}

###
GET {{host}}/

###
GET {{host}}/kugs

###
POST {{host}}/kugs

### Prometheus Metrics
GET {{host}}/metrics

### Healthcheck
GET {{host}}/healthcheck

### Test
GET {{host}}/test

### Home Page
GET {{host}}/home
