server {
    location = /rss.xml {
        types { } default_type "application/atom+xml; charset=utf-8";
    }

    location = /rss-full.xml {
        types { } default_type "application/atom+xml; charset=utf-8";
    }
}
