import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    const val remark_kotlin: String = "by.heap.remark:remark-kotlin:" + Versions.remark_kotlin

    /**
     * http://logback.qos.ch */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    /**
     * https://github.com/atlassian/commonmark-java */
    const val commonmark_ext_gfm_tables: String =
            "com.atlassian.commonmark:commonmark-ext-gfm-tables:" +
            Versions.com_atlassian_commonmark

    /**
     * https://github.com/atlassian/commonmark-java */
    const val commonmark: String = "com.atlassian.commonmark:commonmark:" +
            Versions.com_atlassian_commonmark

    /**
     * http://wiki.fasterxml.com/JacksonExtensionXmlDataBinding */
    const val jackson_dataformat_xml: String =
            "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:" +
            Versions.jackson_dataformat_xml

    /**
     * https://github.com/FasterXML/jackson-module-kotlin */
    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:" + Versions.jackson_module_kotlin

    /**
     * https://github.com/dfabulich/sitemapgen4j/ */
    const val sitemapgen4j: String = "com.github.dfabulich:sitemapgen4j:" + Versions.sitemapgen4j

    /**
     * http://rometools.com */
    const val rome: String = "com.rometools:rome:" + Versions.rome

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/${github.repo} */
    const val sentry_logback: String = "io.sentry:sentry-logback:" + Versions.sentry_logback

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-compiler-embeddable:" + Versions.kotlin_compiler_embeddable

    /**
     * https://kotlinlang.org/ */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.kotlin_reflect

    /**
     * https://kotlinlang.org/ */
    const val kotlin_script_util: String = "org.jetbrains.kotlin:kotlin-script-util:" +
            Versions.kotlin_script_util

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.kotlin_scripting_compiler_embeddable

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.kotlin_stdlib_jdk8

    /**
     * https://github.com/Kotlin/kotlinx.coroutines */
    const val kotlinx_coroutines_jdk8: String = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:" +
            Versions.kotlinx_coroutines_jdk8

    /**
     * https://jsoup.org/ */
    const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup

    /**
     * http://www.slf4j.org */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api
}
