/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ArticleTopic(
    var articleId: Long? = null,
    var topicId: Long? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ArticleTopic = other as ArticleTopic
        if (this.articleId == null) {
            if (o.articleId != null)
                return false
        }
        else if (this.articleId != o.articleId)
            return false
        if (this.topicId == null) {
            if (o.topicId != null)
                return false
        }
        else if (this.topicId != o.topicId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.articleId == null) 0 else this.articleId.hashCode())
        result = prime * result + (if (this.topicId == null) 0 else this.topicId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ArticleTopic (")

        sb.append(articleId)
        sb.append(", ").append(topicId)

        sb.append(")")
        return sb.toString()
    }
}
