/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ArticleKotlinVersion(
    var articleId: Long? = null,
    var kotlinVersionId: Long? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ArticleKotlinVersion = other as ArticleKotlinVersion
        if (this.articleId == null) {
            if (o.articleId != null)
                return false
        }
        else if (this.articleId != o.articleId)
            return false
        if (this.kotlinVersionId == null) {
            if (o.kotlinVersionId != null)
                return false
        }
        else if (this.kotlinVersionId != o.kotlinVersionId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.articleId == null) 0 else this.articleId.hashCode())
        result = prime * result + (if (this.kotlinVersionId == null) 0 else this.kotlinVersionId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ArticleKotlinVersion (")

        sb.append(articleId)
        sb.append(", ").append(kotlinVersionId)

        sb.append(")")
        return sb.toString()
    }
}
