/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class BookLibrary(
    var bookId: Long? = null,
    var libraryId: Long? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BookLibrary = other as BookLibrary
        if (this.bookId == null) {
            if (o.bookId != null)
                return false
        }
        else if (this.bookId != o.bookId)
            return false
        if (this.libraryId == null) {
            if (o.libraryId != null)
                return false
        }
        else if (this.libraryId != o.libraryId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.bookId == null) 0 else this.bookId.hashCode())
        result = prime * result + (if (this.libraryId == null) 0 else this.libraryId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BookLibrary (")

        sb.append(bookId)
        sb.append(", ").append(libraryId)

        sb.append(")")
        return sb.toString()
    }
}
