/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class EntityTopic(
    var entityId: Long? = null,
    var topic: String? = null,
    var created: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: EntityTopic = other as EntityTopic
        if (this.entityId == null) {
            if (o.entityId != null)
                return false
        }
        else if (this.entityId != o.entityId)
            return false
        if (this.topic == null) {
            if (o.topic != null)
                return false
        }
        else if (this.topic != o.topic)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.entityId == null) 0 else this.entityId.hashCode())
        result = prime * result + (if (this.topic == null) 0 else this.topic.hashCode())
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("EntityTopic (")

        sb.append(entityId)
        sb.append(", ").append(topic)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
