/*
 * This file is generated by jOOQ.
 */
package link.kotlin.server.jooq.main.tables.records


import java.time.OffsetDateTime

import link.kotlin.server.jooq.main.tables.EntityTag

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EntityTagRecord() : TableRecordImpl<EntityTagRecord>(EntityTag.ENTITY_TAG) {

    open var entityId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var tag: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var created: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    /**
     * Create a detached, initialised EntityTagRecord
     */
    constructor(entityId: Long? = null, tag: String? = null, created: OffsetDateTime? = null): this() {
        this.entityId = entityId
        this.tag = tag
        this.created = created
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised EntityTagRecord
     */
    constructor(value: link.kotlin.server.jooq.main.tables.pojos.EntityTag?): this() {
        if (value != null) {
            this.entityId = value.entityId
            this.tag = value.tag
            this.created = value.created
            resetChangedOnNotNull()
        }
    }
}
