/*
 * This file is generated by jOOQ.
 */
package link.kotlin.server.jooq.main.tables.daos


import kotlin.collections.List

import link.kotlin.server.jooq.main.tables.CourseSpeaker
import link.kotlin.server.jooq.main.tables.records.CourseSpeakerRecord

import org.jooq.Configuration
import org.jooq.Record2
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourseSpeakerDao(configuration: Configuration?) : DAOImpl<CourseSpeakerRecord, link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker, Record2<Long?, Long?>>(CourseSpeaker.COURSE_SPEAKER, link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker::class.java, configuration) {

    /**
     * Create a new CourseSpeakerDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker): Record2<Long?, Long?> = compositeKeyRecord(o.courseId, o.kotlinerId)

    /**
     * Fetch records that have <code>course_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCourseId(lowerInclusive: Long?, upperInclusive: Long?): List<link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker> = fetchRange(CourseSpeaker.COURSE_SPEAKER.COURSE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>course_id IN (values)</code>
     */
    fun fetchByCourseId(vararg values: Long): List<link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker> = fetch(CourseSpeaker.COURSE_SPEAKER.COURSE_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>kotliner_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfKotlinerId(lowerInclusive: Long?, upperInclusive: Long?): List<link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker> = fetchRange(CourseSpeaker.COURSE_SPEAKER.KOTLINER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>kotliner_id IN (values)</code>
     */
    fun fetchByKotlinerId(vararg values: Long): List<link.kotlin.server.jooq.main.tables.pojos.CourseSpeaker> = fetch(CourseSpeaker.COURSE_SPEAKER.KOTLINER_ID, *values.toTypedArray())
}
