@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package jooq.main.tables.references


import jooq.main.tables.FlywaySchemaHistory
import jooq.main.tables.KotlinVersion
import jooq.main.tables.Kotliner
import jooq.main.tables.Kug



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.kotlin_version</code>.
 */
val KOTLIN_VERSION: KotlinVersion = KotlinVersion.KOTLIN_VERSION

/**
 * The table <code>public.kotliner</code>.
 */
val KOTLINER: Kotliner = Kotliner.KOTLINER

/**
 * The table <code>public.kug</code>.
 */
val KUG: Kug = Kug.KUG
